### ISSUE TITLE
Tests missing critical schemas due to being namespaced

### ISSUE THREAD

**Issue by ShirMonDT** [datreeio/kubectl-datree#4]
Hello!

I've started using this plugin to test compatibility of my cluster to 1.22 and noticed that since this is namespaced it's missing CRDs! These are super critical, could there be an option to do a full cluster scan regardless of namespace that goes over ALL my cluster resources?

**Comment by hadar-co** [comment]
Hi @ShirMonDT!
This plugin does not support CRDs, only native k8s resources (see the readme in this repo for the list of supported resources).
Even if your CRDs were to be extracted and tested, specifying version 1.22 would not do much good, since they would be tested against the same schema (since we have no way of getting other schema versions of CRDs).

Hope this answered your question:)

**Comment by ShirMonDT** [comment]
I see, really CRDs are native k8s resources, the CRs aren't, so is there no plan to support cluster-wide resources?

**Comment by hadar-co** [comment]
Oh I see, I misunderstood you, I thought you meant testing the actual CRs.
As for the CRDs themselves, it is quite a simple fix to support testing them as well, we will prioritize this and add the fix:)

**Comment by ShirMonDT** [comment]
Great! Will this also allow me to perform a full cluster scan without specifying namespace?

**Comment by hadar-co** [comment]
No, but we will consider adding that capability as well.
In the meantime you can try a workaround - create a bash script that iterates over all of your namespaces, and runs the plugin on each of them.
`kubectl get namespace -o name` will give you all of them.

**Comment by hadar-co** [comment]
@ShirMonDT a new version of the plugin is now available, it tests CRDs as well as the other native resources:)

Regarding cluster wide testing - I will open a feature request for it 😎
